### ISSUE TITLE
The leading '<' stays open for all the tags.

### ISSUE THREAD

**Issue by tzsk** [mrmartineau/HTML5#22] opened 2015-08-07 08:21 UTC
If I try to type '<' then it surely gives me the <div> option. But when I select it then this thing is getting created '<<div></div>' (Notice: The leading '<'). It would be a big help if you fix it.

**Comment by mrmartineau** [comment] 2015-08-07 11:45
Can you paste some output please?

**Comment by tzsk** [comment] 2015-08-09 08:25
When I try typing '&lt;div' and press enter then it successfully gives me DIV but with a leading '&lt;'
Here is the example: 
&lt;&lt;div&gt;

&lt;/div&gt;

Here is the Snip:
![gt](https://cloud.githubusercontent.com/assets/13273787/9154102/526f138a-3e9e-11e5-9c76-c25fbecd7a3b.PNG)

But when I type: 'div' and hit 'tab' then it shows correctly. Perfectly.

This happens not just for the 'DIV' but for all the tags.... 
'&lt;input'+Enter gives: '&lt;&lt;input type="text" name="" value="" placeholder=""&gt;'
etc. etc.

**Comment by mrmartineau** [comment] 2015-08-09 08:55
Hi @kazi-mainuddin-ahmed, to fix the issue, you should omit the first `<` because all these snippets use the tag name, e.g. `div` as the trigger. The [readme](https://github.com/mrmartineau/HTML5#how-to-use-the-snippets) actually mentions this. I am going to close this ticket because it is done this way by design and so is not a bug.

**Closed as completed by mrmartineau** 2015-08-09 08:55 UTC

**Comment by tzsk** [comment] 2015-08-09 09:05
Actually it should work both ways. Just test the previous character if it is a '&lt;' then omit that automatically. Previous Sublime Text versions had same problem with their built in HTML. But later they solved it.

Anyway... Thanks.

**Comment by mrmartineau** [comment] 2015-08-09 09:13
I'm not aware of that feature, but if you know how to implement this, please submit a pull a request & I will gladly add it
