### ISSUE TITLE
The automatic completion makes a double inferior quote in ST3

### ISSUE THREAD

**Issue by swirly** [mrmartineau/HTML5#23] opened 2016-02-11 10:25 UTC
In ST3, the automatic completion propose for <bo to add the body tag
(automatic completion first default line : body .... <body>)
but the result is

<<body></body>

with two opening tags

Does not happen if HTML is disabled

if HTML5 is enabled and HTML disabled, nothing is working

**Comment by jmenglis** [comment] 2016-03-01 16:36
I concur with Swirly.  I have seen this same issue with both HTML5 and HTML enabled.  The problem with disabling HTML is that all the syntax highlighting in Sublime disappears.

**Comment by ghost** [comment] 2016-03-28 10:42
This "double quote" problem **trashes ST3** on PC and Mac for inline HTML coding. It is actually ST2 and ST3 issue (severity sometimes depending on OS/WIN Cloud Service relationships) that may have something to do with the PY authors (i.e., developers building Sublime Text) pushing through development that damages "entry level" code entry. Namely, **built-in HTML snippets** corrupt Sublime HTML code, by auto insertion of additional character, as described below (see below, historical information). 
Regardless of cause, the ISSUE IS THIS: 

&lt;div&gt;

entered manually remains as entered, a healthy div element HTML tag.
However, 

&lt;d

and then **coder selection of any of the cursor drop-down built in '&lt;tag&gt;' snippets**, 
consistently inserts the additional character, namely:

&lt;&lt;div&gt;

Now, when this problem first appeared in ST2, one did not have to use the snippets, 
just **closing any HTML element tag did auto-insert the corrupt additional code character**, 
as described above.
Today, this corruption is found upon use of the snippet functionality, 
in entry of any and all HTML element tags inside of the &lt;body&gt; tag.
Here is the description of the corrupt character auto-inserted by every default Sublime configuration:

**LESS-THAN SIGN
Sublime script: wtf knows?
Latin: left carat symbol
HTML: <, &lt, &lt ;
Unicode: U+003C, UTF-8: 3C
Hex: &#x0003c
Dec: &#60**

That is, assuming use of the default expected Sublime configuration (as shipped) then
whenever built in HTML snippets are accessed by all users from code insertion point, 
then corrupt by default, Sublime auto inserts the additional opening Left Carat symbol.
This corrupt Sublime auto insertion of &lt;&lt; can be just 50% of HTML &lt; characters typed into Sublime code.
Most often it is most, if not all HTML element opening tags inside of the &lt;body&gt; tag 
(all opening tags are corrupted by Sublime). 
Though, addition of any Package (including HTML5 Package), 
definitely worsens the default Sublime corruption.

This leaves the Sublime HTML coder in the unfortunate predicament that the cursor **'|'** is at 
the **far right of the element-attribute tag**, 
while the incorrectly inserted additional left carat is at 
the **far left of the element-attribute tag**! 
Auto inserting of the extra left carat occurs in Sublime HTML coding like this:

**&lt;&lt;div&gt;|**
and
**&lt;&lt;div attribute="something"&gt;|**
or, given _a { word-wrap: break-word; }_,
**&lt;&lt;a href="https://www.google.ca/search?q=very+long+html+link&client=safari&rls=en&source=lnms&tbm=isch&sa=X&ved=0ahUKEwj18q72_OLLAhVM1GMKHYtRDgEQ_AUIBygB" 
style="colour: red; 
content: "(" attr(href) ")"; 
font-size: 0.9rem; 
font-weight: 700; 
letter-spacing: 0.13ex; 
list-style-image: url(http://example.org/pix/checkmark.png);"> |**
[hey stoopid monkey, you beginning to dig our pissed-off "attitude"]

This crap HTML coding has been a problem in Sublime for years, literal years!
Now, if you ask me, an "entry level" coder for life, 
this is brain dead on the part of the Sublime App developers - well, yes? No?
Okay, but they are obviously PY-BLIND, 
and cannot see how they have mangled Sublime Text, 
as their "entry level" coding product cannot shake a simple but serious problem.
Or perhaps they can see what they have done, and **don't give a shit**.
"Don't give a shit!" is definitely the tenure of Sublime developers at GitHub, 
interacting with my requests (arrogant, ignorant PY-BLIND developers).
Microsoft senior engineers, who referred me to Sublime, were "GUM-FUK'd".

In all fairness, the PY-BLIND may be stuck where we all code due to environment.
Or, the brain-dead PY-BLIND developers may all be sharing some 
secret plug-in or package that removes the HTML coding corruption, 
on their highly privileged devices.
Then again, they could be too thoughtless to look outside some kind of paranoid shell.
And, in all fairness, they could be not only assailed and maladjusted persons, 
but they could honestly feel, 

**"Shit on them all! They could always be running after 
Edit, Replace, <<, tab, <, over-and-over all day long 
so they can preview their puny work!"**

**You thunk?**

Fact is, Sublime's a spastic mess for all HTML coders using default Sublime configuration. 
Let's don't forgive our frustration, and leave it at that.
Let's fix that corrupt HTML auto-insertion of the corrupt opening HTML tag character.
That's all affirmative here. You, @mrmartineau ?

**Comment by cmalard** [comment] 2017-07-14 02:10
Hello there,
Could this be fixed with the ST3 [.sublime-syntax](http://www.sublimetext.com/docs/3/syntax.html) files ?

**Comment by resende1776** [comment] 2017-10-05 11:25
Same problem here. 

> Edit, Replace, <<, tab, <, over-and-over

It keeps killing me, but that's all I got

**Comment by KonradBartu** [comment] 2017-10-22 15:26
> Don't type the opening bracket:
> i.e.
> **<h1 + tab**
> Instead just type:
> **h1 + tab**
> Autocompletion will work and you won't get the extra **<**

**Comment by kileyohl** [comment] 2018-12-05 16:17
Anyone ever find a solution or other plugin for this? It has bothered me for YEARS and seems SO fixable- No? SUCH a great plugin, but can't use like this.

**Closed as completed** 2018-12-05 22:54 UTC
